version: "3"
services:
  database:
    image: "postgres"
    restart: always
    container_name: "database"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adm1n
      - POSTGRES_DB=activity
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - database
    image: filipkraljevski/kiiiproject-app:latest
    container_name: "app"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/activity"
volumes:
  postgres-data: