apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: kiii
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      - host: 203141.finki.mk
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: spring-service
                  port:
                    number: 8080